### ISSUE TITLE
Fix languishing issues from nonsequitur/smex

### ISSUE THREAD

**Issue by DarwinAwardWinner** [DarwinAwardWinner/smex#1]
Need to either fix/merge or decided not to handle the following:

Trivial fixes:

- [x] nonsequitur/smex#62 Fix the default for smex-save-file given in README
- [x] nonsequitur/smex#54 Update MELPA URL

Easy/ready to merge:

- [x] nonsequitur/smex#11 Add global minor mode with autoloads
- [x] nonsequitur/smex#12 Use customize to simplify startup (see also 66)
- [x] nonsequitur/smex#66 Add smex-mode, a global minor mode (see also 12)
- [x] nonsequitur/smex#68 Require a match when completing commands
- [x] nonsequitur/smex#63 missing dependency: ido-completing-read+.el 
- [x] nonsequitur/smex#67 Smart update

Harder/more involved:

- [x] nonsequitur/smex#58 Custom ido bindings stop working with Smex installed
- [x] nonsequitur/smex#57 Smex forces ido-max-prospects 10
- [x] nonsequitur/smex#46 Feature request: typing a space inserts a hyphen ‘-’
- [x] nonsequitur/smex#53 Feature request: show keybindings
- [x] nonsequitur/smex#55 Show keybindings in smex results.
- [x] nonsequitur/smex#20 Filter out unwanted commands from smex completions
- [x] nonsequitur/smex#65 smex caused multiple-cursors incorrect behavior

**Comment by DarwinAwardWinner** [comment]
- [x] Also browse this for juicy morsels: https://github.com/DarwinAwardWinner/smex/network
  - [x] https://github.com/JacksonGariety/smex/commit/81c1582fff7b8b297237cdbe79405a54db9d7434
  - [x] https://github.com/vspinu/smex/commit/699c062b20c491c13c49fdcf61c59c239d6a0e54

**Comment by DarwinAwardWinner** [comment]
- 57: removed the offending code
- 46: already implemented by http://melpa.org/#/ido-complete-space-or-hyphen
- 58: cannot reproduce
- 65: I don't use multiple cursors, so I'm not qualified to debug this
